name: Run R Script Daily

on:
  schedule:
    - cron: '0 9,14 * * *'  # Runs at 9 AM and 2 PM UTC daily
  workflow_dispatch:        # Allows manual triggering

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.2.0  # Uses R version 4.2.0

    steps:
      # Checkout the repository to access your script
      - uses: actions/checkout@v2

      # Install R packages (if needed)
      - name: Install R packages
        run: |
          Rscript -e 'install.packages("rvest")'
          Rscript -e 'install.packages("blastula")'
          Rscript -e 'install.packages("glue")'
          Rscript -e 'install.packages("httr")'
          Rscript -e 'install.packages("keyring")'

      # Run the R script
      - name: Run R script
        run: Rscript Alert_test.R
